# Rusty-Stack build helper

.DEFAULT_GOAL := build

build:
	@cd ../rusty-stack && cargo build --release
	@echo "Built Rusty-Stack: ../rusty-stack/target/release/rusty-stack"

run:
	@../scripts/run_rusty_stack.sh
